# Generated by Django 5.0.6 on 2024-05-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='products',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='profile',
        ),
        migrations.DeleteModel(
            name='InvoiceProduct',
        ),
    ]
