# Generated by Django 5.0.3 on 2024-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='location',
            new_name='title',
        ),
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='logoUrl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
