# Generated by Django 5.0.3 on 2024-03-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_address_profile_mobile_profile_phone_and_more'),
        ('shops', '0002_rename_location_shop_title_shop_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
