# Generated by Django 5.0.3 on 2024-03-25 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shop_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.product')),
            ],
        ),
    ]
