# Generated by Django 5.0.3 on 2024-04-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_tag_rename_product_name_product_name_product_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='shop',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
