# Generated by Django 5.0.3 on 2024-04-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_rename_shop_name_shop_name_shop_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
