# Generated by Django 4.1.13 on 2024-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_product_images_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_imagesm', to='shops.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shops.tag'),
        ),
    ]
