# Generated by Django 4.1.13 on 2024-04-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_alter_shop_data'),
        ('shops', '0010_alter_product_images_alter_product_tags'),
    ]

    operations = [
    ]
