# Generated by Django 4.1.13 on 2024-04-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_merge_20240415_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(default='no_image.jpg', upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_images', to='shops.productimage'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
