# Generated by Django 5.0.3 on 2024-03-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_invoiceproduct_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
