# Generated by Django 4.1.13 on 2024-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_invoiceproduct_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='socials',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Seller', 'Seller')], default='Client', max_length=10),
        ),
    ]
