# Generated by Django 5.0.3 on 2024-03-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Seller', 'Seller')], default='Client', max_length=10),
        ),
    ]
