# Generated by Django 4.1.13 on 2024-04-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='../../quick-ionic/src/assets/avatar/%Y/%m/%d'),
        ),
    ]
