# Generated by Django 4.1.13 on 2024-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_address_profile_mobile_profile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
