# Generated by Django 4.1.13 on 2024-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_stripe',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
